#server
server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000

#spring
spring:
  datasource:
    url: jdbc:mysql:///jtsys?serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: 123456
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
  aop:
    proxy-target-class: false


#mybatis
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/sys/*.xml

#lOG
logging:
  level:
    com.cy: DEBUG
         
    
    
    
    
    
    